pub struct StmColumn {
    pub name: &'static str,
    pub label: &'static str,
}

pub struct StmTable {
    pub name: &'static str,
    pub label: &'static str,
    pub columns: &'static [StmColumn],
}

pub fn all_tables() -> &'static [StmTable] {
    TABLES
}

pub fn find_table(name: &str) -> Option<&'static StmTable> {
    TABLES.iter().find(|t| t.name == name)
}

static TABLES: &[StmTable] = &[
    // ── Expense ───────────────────────────────────────────────────────────────
    StmTable {
        name: "EXPENSE_REPORT",
        label: "Expense Report Header",
        columns: &[
            StmColumn { name: "REPORT_ID",            label: "Report ID" },
            StmColumn { name: "REPORT_NAME",          label: "Report Name" },
            StmColumn { name: "EMPLOYEE_ID",          label: "Employee ID" },
            StmColumn { name: "LOGIN_ID",             label: "Login (Email)" },
            StmColumn { name: "EMPLOYEE_NAME",        label: "Employee Name" },
            StmColumn { name: "TRIP_ID",              label: "Linked Trip ID" },
            StmColumn { name: "SUBMIT_DATE",          label: "Submit Date" },
            StmColumn { name: "APPROVAL_DATE",        label: "Approval Date" },
            StmColumn { name: "PAYMENT_DATE",         label: "Payment Date" },
            StmColumn { name: "REPORT_TOTAL",         label: "Report Total" },
            StmColumn { name: "APPROVED_AMOUNT",      label: "Approved Amount" },
            StmColumn { name: "CURRENCY_CODE",        label: "Currency Code" },
            StmColumn { name: "REPORT_STATUS_CODE",   label: "Status Code" },
            StmColumn { name: "COST_CENTER_CODE",     label: "Cost Center" },
            StmColumn { name: "POLICY_ID",            label: "Policy ID" },
            StmColumn { name: "BUSINESS_PURPOSE",     label: "Business Purpose" },
            StmColumn { name: "COUNTRY_CODE",         label: "Country Code" },
            StmColumn { name: "CREATE_DATE",          label: "Created Date" },
        ],
    },
    StmTable {
        name: "EXPENSE_ENTRY",
        label: "Expense Entry (Line Items)",
        columns: &[
            StmColumn { name: "REPORT_ID",              label: "Report ID" },
            StmColumn { name: "ENTRY_ID",               label: "Entry ID" },
            StmColumn { name: "CARD_TRANSACTION_ID",    label: "Card Transaction ID" },
            StmColumn { name: "EXPENSE_TYPE_CODE",      label: "Expense Type Code" },
            StmColumn { name: "EXPENSE_TYPE_NAME",      label: "Expense Type Name" },
            StmColumn { name: "TRANSACTION_DATE",       label: "Transaction Date" },
            StmColumn { name: "TRANSACTION_AMOUNT",     label: "Transaction Amount" },
            StmColumn { name: "TRANSACTION_CURRENCY",   label: "Transaction Currency" },
            StmColumn { name: "APPROVED_AMOUNT",        label: "Approved Amount" },
            StmColumn { name: "APPROVED_CURRENCY",      label: "Approved Currency" },
            StmColumn { name: "PAYMENT_TYPE_CODE",      label: "Payment Type" },
            StmColumn { name: "VENDOR_DESCRIPTION",     label: "Vendor / Description" },
            StmColumn { name: "CITY_OF_PURCHASE",       label: "City of Purchase" },
            StmColumn { name: "COUNTRY_CODE",           label: "Country Code" },
            StmColumn { name: "RECEIPT_REQUIRED",       label: "Receipt Required (Y/N)" },
            StmColumn { name: "RECEIPT_RECEIVED",       label: "Receipt Received (Y/N)" },
            StmColumn { name: "IS_PERSONAL",            label: "Personal Expense (Y/N)" },
            StmColumn { name: "HAS_EXCEPTION",          label: "Has Policy Exception (Y/N)" },
            StmColumn { name: "COMMENT",                label: "Comment" },
        ],
    },
    StmTable {
        name: "EXPENSE_ITEMIZATION",
        label: "Expense Itemization (Hotel Nightly, etc.)",
        columns: &[
            StmColumn { name: "REPORT_ID",          label: "Report ID" },
            StmColumn { name: "ENTRY_ID",           label: "Parent Entry ID" },
            StmColumn { name: "ITEMIZATION_ID",     label: "Itemization ID" },
            StmColumn { name: "EXPENSE_TYPE_CODE",  label: "Expense Type Code" },
            StmColumn { name: "EXPENSE_TYPE_NAME",  label: "Expense Type Name" },
            StmColumn { name: "TRANSACTION_DATE",   label: "Date" },
            StmColumn { name: "TRANSACTION_AMOUNT", label: "Amount" },
            StmColumn { name: "CURRENCY_CODE",      label: "Currency Code" },
            StmColumn { name: "COMMENT",            label: "Comment" },
        ],
    },
    StmTable {
        name: "EXPENSE_ALLOCATION",
        label: "Expense Cost Allocation",
        columns: &[
            StmColumn { name: "REPORT_ID",        label: "Report ID" },
            StmColumn { name: "ENTRY_ID",         label: "Entry ID" },
            StmColumn { name: "ALLOCATION_ID",    label: "Allocation ID" },
            StmColumn { name: "COST_CENTER",      label: "Cost Center" },
            StmColumn { name: "GL_ACCOUNT",       label: "G/L Account" },
            StmColumn { name: "PROJECT_CODE",     label: "Project Code" },
            StmColumn { name: "PERCENTAGE",       label: "Allocation Percentage" },
            StmColumn { name: "AMOUNT",           label: "Allocated Amount" },
            StmColumn { name: "CURRENCY_CODE",    label: "Currency Code" },
            StmColumn { name: "CUSTOM_FIELD_1",   label: "Custom Field 1" },
            StmColumn { name: "CUSTOM_FIELD_2",   label: "Custom Field 2" },
        ],
    },
    StmTable {
        name: "EXPENSE_ATTENDEE",
        label: "Expense Attendees",
        columns: &[
            StmColumn { name: "REPORT_ID",         label: "Report ID" },
            StmColumn { name: "ENTRY_ID",          label: "Entry ID" },
            StmColumn { name: "ATTENDEE_ID",       label: "Attendee ID" },
            StmColumn { name: "ATTENDEE_TYPE",     label: "Attendee Type" },
            StmColumn { name: "FIRST_NAME",        label: "First Name" },
            StmColumn { name: "LAST_NAME",         label: "Last Name" },
            StmColumn { name: "COMPANY",           label: "Company" },
            StmColumn { name: "TITLE",             label: "Title" },
            StmColumn { name: "AMOUNT",            label: "Amount Per Attendee" },
            StmColumn { name: "CURRENCY_CODE",     label: "Currency Code" },
        ],
    },
    StmTable {
        name: "CORPORATE_CARD_TRANSACTION",
        label: "Corporate Card Transaction",
        columns: &[
            StmColumn { name: "TRANSACTION_ID",       label: "Transaction ID" },
            StmColumn { name: "CARD_NUMBER_LAST4",    label: "Card Number (Last 4)" },
            StmColumn { name: "EMPLOYEE_ID",          label: "Employee ID" },
            StmColumn { name: "LOGIN_ID",             label: "Login (Email)" },
            StmColumn { name: "TRANSACTION_DATE",     label: "Transaction Date" },
            StmColumn { name: "POST_DATE",            label: "Post Date" },
            StmColumn { name: "MERCHANT_NAME",        label: "Merchant Name" },
            StmColumn { name: "MERCHANT_CATEGORY",    label: "Merchant Category Code" },
            StmColumn { name: "TRANSACTION_AMOUNT",   label: "Transaction Amount" },
            StmColumn { name: "CURRENCY_CODE",        label: "Currency Code" },
            StmColumn { name: "MATCH_STATUS",         label: "Match Status (Matched/Unmatched)" },
            StmColumn { name: "REPORT_ID",            label: "Matched Report ID" },
            StmColumn { name: "ENTRY_ID",             label: "Matched Entry ID" },
        ],
    },
    StmTable {
        name: "CASH_ADVANCE",
        label: "Cash Advance",
        columns: &[
            StmColumn { name: "ADVANCE_ID",        label: "Advance ID" },
            StmColumn { name: "REPORT_ID",         label: "Linked Report ID" },
            StmColumn { name: "EMPLOYEE_ID",       label: "Employee ID" },
            StmColumn { name: "LOGIN_ID",          label: "Login (Email)" },
            StmColumn { name: "REQUEST_DATE",      label: "Request Date" },
            StmColumn { name: "ISSUE_DATE",        label: "Issue Date" },
            StmColumn { name: "ADVANCE_AMOUNT",    label: "Advance Amount" },
            StmColumn { name: "CURRENCY_CODE",     label: "Currency Code" },
            StmColumn { name: "ADVANCE_STATUS",    label: "Status" },
            StmColumn { name: "SETTLEMENT_DATE",   label: "Settlement Date" },
            StmColumn { name: "BALANCE_AMOUNT",    label: "Outstanding Balance" },
        ],
    },
    // ── Travel Requests ───────────────────────────────────────────────────────
    StmTable {
        name: "TRAVEL_REQUEST",
        label: "Travel Request Header",
        columns: &[
            StmColumn { name: "REQUEST_ID",             label: "Request ID" },
            StmColumn { name: "REQUEST_NAME",           label: "Request Name" },
            StmColumn { name: "EMPLOYEE_ID",            label: "Employee ID" },
            StmColumn { name: "LOGIN_ID",               label: "Login (Email)" },
            StmColumn { name: "SUBMIT_DATE",            label: "Submit Date" },
            StmColumn { name: "APPROVAL_DATE",          label: "Approval Date" },
            StmColumn { name: "START_DATE",             label: "Trip Start Date" },
            StmColumn { name: "END_DATE",               label: "Trip End Date" },
            StmColumn { name: "DESTINATION",            label: "Destination" },
            StmColumn { name: "TOTAL_APPROVED_AMOUNT",  label: "Total Approved Amount" },
            StmColumn { name: "CURRENCY_CODE",          label: "Currency Code" },
            StmColumn { name: "REQUEST_STATUS_CODE",    label: "Status Code" },
            StmColumn { name: "TRIP_PURPOSE",           label: "Trip Purpose" },
            StmColumn { name: "POLICY_ID",              label: "Policy ID" },
            StmColumn { name: "COUNTRY_CODE",           label: "Country Code" },
        ],
    },
    StmTable {
        name: "TRAVEL_REQUEST_SEGMENT",
        label: "Travel Request Segments",
        columns: &[
            StmColumn { name: "REQUEST_ID",        label: "Request ID" },
            StmColumn { name: "SEGMENT_ID",        label: "Segment ID" },
            StmColumn { name: "SEGMENT_TYPE",      label: "Segment Type (AIR/HOTEL/CAR/RAIL)" },
            StmColumn { name: "DEPARTURE_DATE",    label: "Departure Date" },
            StmColumn { name: "ARRIVAL_DATE",      label: "Arrival Date" },
            StmColumn { name: "ORIGIN",            label: "Origin" },
            StmColumn { name: "DESTINATION",       label: "Destination" },
            StmColumn { name: "VENDOR_CODE",       label: "Vendor Code" },
            StmColumn { name: "VENDOR_NAME",       label: "Vendor Name" },
            StmColumn { name: "ESTIMATED_AMOUNT",  label: "Estimated Amount" },
            StmColumn { name: "CURRENCY_CODE",     label: "Currency Code" },
            StmColumn { name: "BOOKING_STATUS",    label: "Booking Status" },
        ],
    },
    // ── Travel Bookings (actual booked itineraries) ───────────────────────────
    StmTable {
        name: "TRIP",
        label: "Booked Travel Itinerary",
        columns: &[
            StmColumn { name: "TRIP_ID",           label: "Trip ID" },
            StmColumn { name: "EMPLOYEE_ID",       label: "Employee ID" },
            StmColumn { name: "LOGIN_ID",          label: "Login (Email)" },
            StmColumn { name: "REQUEST_ID",        label: "Linked Request ID" },
            StmColumn { name: "TRIP_NAME",         label: "Trip Name" },
            StmColumn { name: "BOOKING_DATE",      label: "Booking Date" },
            StmColumn { name: "START_DATE",        label: "Trip Start Date" },
            StmColumn { name: "END_DATE",          label: "Trip End Date" },
            StmColumn { name: "DESTINATION",       label: "Primary Destination" },
            StmColumn { name: "TOTAL_COST",        label: "Total Booked Cost" },
            StmColumn { name: "CURRENCY_CODE",     label: "Currency Code" },
            StmColumn { name: "TRIP_STATUS",       label: "Trip Status" },
            StmColumn { name: "PNR_LOCATOR",       label: "PNR Locator" },
            StmColumn { name: "TMC_NAME",          label: "Travel Management Company" },
        ],
    },
    StmTable {
        name: "TRIP_SEGMENT_AIR",
        label: "Booked Air Segment",
        columns: &[
            StmColumn { name: "TRIP_ID",            label: "Trip ID" },
            StmColumn { name: "SEGMENT_ID",         label: "Segment ID" },
            StmColumn { name: "AIRLINE_CODE",       label: "Airline Code" },
            StmColumn { name: "AIRLINE_NAME",       label: "Airline Name" },
            StmColumn { name: "FLIGHT_NUMBER",      label: "Flight Number" },
            StmColumn { name: "ORIGIN_AIRPORT",     label: "Origin Airport (IATA)" },
            StmColumn { name: "DEST_AIRPORT",       label: "Destination Airport (IATA)" },
            StmColumn { name: "DEPARTURE_DATETIME", label: "Departure Date/Time" },
            StmColumn { name: "ARRIVAL_DATETIME",   label: "Arrival Date/Time" },
            StmColumn { name: "CABIN_CLASS",        label: "Cabin Class" },
            StmColumn { name: "FARE_BASIS",         label: "Fare Basis Code" },
            StmColumn { name: "TICKET_NUMBER",      label: "Ticket Number" },
            StmColumn { name: "FARE_AMOUNT",        label: "Fare Amount" },
            StmColumn { name: "CURRENCY_CODE",      label: "Currency Code" },
            StmColumn { name: "BOOKING_STATUS",     label: "Booking Status" },
            StmColumn { name: "IS_OUT_OF_POLICY",   label: "Out of Policy (Y/N)" },
        ],
    },
    StmTable {
        name: "TRIP_SEGMENT_HOTEL",
        label: "Booked Hotel Segment",
        columns: &[
            StmColumn { name: "TRIP_ID",            label: "Trip ID" },
            StmColumn { name: "SEGMENT_ID",         label: "Segment ID" },
            StmColumn { name: "PROPERTY_NAME",      label: "Property Name" },
            StmColumn { name: "CHAIN_CODE",         label: "Hotel Chain Code" },
            StmColumn { name: "CITY",               label: "City" },
            StmColumn { name: "COUNTRY_CODE",       label: "Country Code" },
            StmColumn { name: "CHECK_IN_DATE",      label: "Check-In Date" },
            StmColumn { name: "CHECK_OUT_DATE",     label: "Check-Out Date" },
            StmColumn { name: "NIGHTS",             label: "Number of Nights" },
            StmColumn { name: "NIGHTLY_RATE",       label: "Nightly Rate" },
            StmColumn { name: "TOTAL_AMOUNT",       label: "Total Amount" },
            StmColumn { name: "CURRENCY_CODE",      label: "Currency Code" },
            StmColumn { name: "RATE_CODE",          label: "Rate Code" },
            StmColumn { name: "BOOKING_STATUS",     label: "Booking Status" },
            StmColumn { name: "IS_OUT_OF_POLICY",   label: "Out of Policy (Y/N)" },
        ],
    },
    StmTable {
        name: "TRIP_SEGMENT_CAR",
        label: "Booked Car Rental Segment",
        columns: &[
            StmColumn { name: "TRIP_ID",            label: "Trip ID" },
            StmColumn { name: "SEGMENT_ID",         label: "Segment ID" },
            StmColumn { name: "VENDOR_CODE",        label: "Rental Company Code" },
            StmColumn { name: "VENDOR_NAME",        label: "Rental Company Name" },
            StmColumn { name: "PICKUP_LOCATION",    label: "Pickup Location" },
            StmColumn { name: "DROPOFF_LOCATION",   label: "Drop-off Location" },
            StmColumn { name: "PICKUP_DATETIME",    label: "Pickup Date/Time" },
            StmColumn { name: "DROPOFF_DATETIME",   label: "Drop-off Date/Time" },
            StmColumn { name: "CAR_CLASS",          label: "Car Class" },
            StmColumn { name: "DAILY_RATE",         label: "Daily Rate" },
            StmColumn { name: "TOTAL_AMOUNT",       label: "Total Amount" },
            StmColumn { name: "CURRENCY_CODE",      label: "Currency Code" },
            StmColumn { name: "BOOKING_STATUS",     label: "Booking Status" },
            StmColumn { name: "IS_OUT_OF_POLICY",   label: "Out of Policy (Y/N)" },
        ],
    },
    // ── Invoice ───────────────────────────────────────────────────────────────
    StmTable {
        name: "INVOICE",
        label: "Invoice Header",
        columns: &[
            StmColumn { name: "INVOICE_ID",           label: "Invoice ID" },
            StmColumn { name: "INVOICE_NUMBER",       label: "Invoice Number" },
            StmColumn { name: "VENDOR_ID",            label: "Vendor ID" },
            StmColumn { name: "VENDOR_NAME",          label: "Vendor Name" },
            StmColumn { name: "LOGIN_ID",             label: "Requester Login (Email)" },
            StmColumn { name: "EMPLOYEE_ID",          label: "Requester Employee ID" },
            StmColumn { name: "INVOICE_DATE",         label: "Invoice Date" },
            StmColumn { name: "RECEIVED_DATE",        label: "Received Date" },
            StmColumn { name: "APPROVAL_DATE",        label: "Approval Date" },
            StmColumn { name: "PAYMENT_DATE",         label: "Payment Date" },
            StmColumn { name: "TOTAL_AMOUNT",         label: "Total Amount" },
            StmColumn { name: "CURRENCY_CODE",        label: "Currency Code" },
            StmColumn { name: "INVOICE_STATUS_CODE",  label: "Status Code" },
            StmColumn { name: "PAYMENT_TERMS",        label: "Payment Terms" },
            StmColumn { name: "PURCHASE_ORDER",       label: "Purchase Order Number" },
        ],
    },
    StmTable {
        name: "INVOICE_LINE",
        label: "Invoice Line Item",
        columns: &[
            StmColumn { name: "INVOICE_ID",       label: "Invoice ID" },
            StmColumn { name: "LINE_ID",          label: "Line ID" },
            StmColumn { name: "DESCRIPTION",      label: "Line Description" },
            StmColumn { name: "QUANTITY",         label: "Quantity" },
            StmColumn { name: "UNIT_PRICE",       label: "Unit Price" },
            StmColumn { name: "LINE_AMOUNT",      label: "Line Amount" },
            StmColumn { name: "CURRENCY_CODE",    label: "Currency Code" },
            StmColumn { name: "GL_ACCOUNT",       label: "G/L Account" },
            StmColumn { name: "TAX_CODE",         label: "Tax Code" },
            StmColumn { name: "TAX_AMOUNT",       label: "Tax Amount" },
        ],
    },
    StmTable {
        name: "INVOICE_ALLOCATION",
        label: "Invoice Cost Allocation",
        columns: &[
            StmColumn { name: "INVOICE_ID",       label: "Invoice ID" },
            StmColumn { name: "LINE_ID",          label: "Line ID" },
            StmColumn { name: "ALLOCATION_ID",    label: "Allocation ID" },
            StmColumn { name: "COST_CENTER",      label: "Cost Center" },
            StmColumn { name: "GL_ACCOUNT",       label: "G/L Account" },
            StmColumn { name: "PROJECT_CODE",     label: "Project Code" },
            StmColumn { name: "PERCENTAGE",       label: "Allocation Percentage" },
            StmColumn { name: "AMOUNT",           label: "Allocated Amount" },
            StmColumn { name: "CURRENCY_CODE",    label: "Currency Code" },
        ],
    },
    // ── Employee / Shared ─────────────────────────────────────────────────────
    StmTable {
        name: "EMPLOYEE",
        label: "Employee Profile",
        columns: &[
            StmColumn { name: "EMPLOYEE_ID",          label: "Employee ID" },
            StmColumn { name: "LOGIN_ID",             label: "Login (Email)" },
            StmColumn { name: "FIRST_NAME",           label: "First Name" },
            StmColumn { name: "LAST_NAME",            label: "Last Name" },
            StmColumn { name: "EMAIL",                label: "Email Address" },
            StmColumn { name: "DEPARTMENT",           label: "Department" },
            StmColumn { name: "COST_CENTER",          label: "Cost Center" },
            StmColumn { name: "MANAGER_EMPLOYEE_ID",  label: "Manager Employee ID" },
            StmColumn { name: "COUNTRY_CODE",         label: "Country Code" },
            StmColumn { name: "CURRENCY_CODE",        label: "Currency Code" },
            StmColumn { name: "EMPLOYEE_STATUS",      label: "Employee Status" },
            StmColumn { name: "POLICY_GROUP",         label: "Policy Group" },
            StmColumn { name: "LEDGER_CODE",          label: "Ledger Code" },
            StmColumn { name: "CUSTOM_FIELD_1",       label: "Custom Field 1" },
        ],
    },
    StmTable {
        name: "PAYMENT_BATCH",
        label: "Payment Batch",
        columns: &[
            StmColumn { name: "BATCH_ID",           label: "Batch ID" },
            StmColumn { name: "REPORT_ID",          label: "Report ID" },
            StmColumn { name: "EMPLOYEE_ID",        label: "Employee ID" },
            StmColumn { name: "PAYMENT_DATE",       label: "Payment Date" },
            StmColumn { name: "PAYMENT_AMOUNT",     label: "Payment Amount" },
            StmColumn { name: "CURRENCY_CODE",      label: "Currency Code" },
            StmColumn { name: "PAYMENT_TYPE",       label: "Payment Type (ACH/CHECK)" },
            StmColumn { name: "PAYMENT_STATUS",     label: "Payment Status" },
            StmColumn { name: "BANK_ACCOUNT_LAST4", label: "Bank Account (Last 4)" },
            StmColumn { name: "CHECK_NUMBER",       label: "Check Number" },
        ],
    },
];
